swagger: "2.0"
info:
  title: API de Categorias
  version: "1.0.0"
  description: Documentação da API para gerenciamento de categorias.

paths:
  /add:
    post:
      summary: Adiciona uma nova categoria
      parameters:
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: Nome da categoria
              usuario:
                type: string
                description: Usuário que está adicionando a categoria
      responses:
        201:
          description: Categoria criada com sucesso
        400:
          description: Erro: campos obrigatórios ausentes ou dados inválidos
        401:
          description: Usuário não autorizado

  /update_category:
    put:
      summary: Atualiza uma categoria existente
      parameters:
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID da categoria
              name:
                type: string
                description: Novo nome da categoria
      responses:
        201:
          description: Categoria atualizada com sucesso
        400:
          description: Erro: campos obrigatórios ausentes ou dados inválidos
        401:
          description: Usuário não autorizado

  /delete/{category}:
    delete:
      summary: Deleta uma categoria
      parameters:
        - name: category
          in: path
          required: true
          type: string
          description: ID da categoria a ser deletada
      responses:
        200:
          description: Categoria excluída com sucesso
        404:
          description: Erro: categoria não encontrada
        401:
          description: Usuário não autorizado

  /get_all:
    get:
      summary: Obtém todas as categorias de um usuário
      parameters:
        - name: usuario
          in: query
          required: true
          type: integer
          description: ID do usuário para obter suas categorias
      responses:
        200:
          description: Lista de categorias do usuário
        404:
          description: Erro: nenhum registro encontrado para o usuário fornecido
        400:
          description: Erro: parâmetro de usuário inválido
        401:
          description: Usuário não autorizado
