swagger: "2.0"
info:
  title: API de Categorias
  version: "1.0.0"
  description: Documentação da API para gerenciamento de categorias.

paths:
  /add:
    post:
      summary: Adiciona uma nova categoria
      parameters:
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: Nome da categoria
              usuario:
                type: int
                description: Usuário que está adicionando a categoria
      responses:
        201:
          description: "Registro inserido com sucesso"
        400:
          description: Todos os campos (nome, usuario) são obrigatórios
        401:
          description: Usuário não autorizado
        404:
          description: "Registro não inserido"
