global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'app2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'app3'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5010']
