# Use uma imagem base com Python
FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder

# Defina o diretório de trabalho dentro do container
WORKDIR /app1

# Copie o arquivo requirements.txt para o container
COPY requirements.txt .

# Instale as dependências do projeto
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

# Copie o restante do código do projeto para o container
COPY . .

# Defina a variável de ambiente para o Flask
ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0

# Comando para rodar a aplicação Flask
CMD ["python3", "run.py"]
