FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder

WORKDIR /app1

RUN apk add --no-cache curl openjdk11 unzip

COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . .

ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["sh", "-c", "pytest && python3 run.py"]
#ENTRYPOINT ["sh", "-c", "pytest --cov=app1 app/tests/ --cov-report=xml --cov-report=html && python3 run.py"]