services:
  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #environment: 
    #  - FLASK_SERVER_ADDR=app1:9091
    #command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    networks:
      - microservicewallet  
    depends_on:
      - app1
      - app2
      
  app1:
    build:
      context: app1
      target: builder
    #stop_signal: SIGINT
    #environment:
    #  - FLASK_SERVER_PORT=9091
    ports:
      - "5000:5000"
    volumes:
      - ./app1:/src
    depends_on:
      - mongo
    networks:
      - microservicewallet
      
  app2:
    build: 
      context: MicroServiceUserData
      target: builder
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=microserviceuserdata
    networks:
      - microservicewallet
  
  db:
    image: postgres:latest
    secrets:
      - postgres-password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - microservicewallet
    environment:
      - POSTGRES_DB=microserviceuserdata
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5432:5432
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db 
    networks:
      - microservicewallet
    
volumes:
  postgres-data:
  mongo-data:

secrets:
  postgres-password:
    file: postgres/password.txt
networks:
  microservicewallet: