services:

  db:
    image: postgres:latest
    secrets:
      - postgres-password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - microservicewallet
    environment:
      - POSTGRES_DB=microserviceuserdata
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    
  app2:
    build: 
      context: MicroServiceUserData
      target: builder
    environment:
      - POSTGRES_DB=microserviceuserdata  
    depends_on:
      - db 
    networks:
      - microservicewallet

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db 
    networks:
      - microservicewallet
      
  app1:
    build:
      context: app1
      target: builder
    volumes:
      - ./app1:/src
    depends_on:
      - mongo
      - app2
    networks:
      - microservicewallet

  app3:
    build:
      context: app3
      target: builder   
    depends_on:
      - app1
      - app2  
    networks:
      - microservicewallet      
  
  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - microservicewallet  
    depends_on:
      - app1
      - app2    
    
volumes:
  postgres-data:
  mongo-data:

secrets:
  postgres-password:
    file: postgres/password.txt
networks:
  microservicewallet: