services:

  db:
    image: postgres:latest
    secrets:
      - postgres-password
    volumes:
      - ./postgres-data/develop:/var/lib/postgresql/data
    networks:
      - microservicewallet_dev
    environment:
      - POSTGRES_DB=microserviceuserdata_dev
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password

  app2:
    image: danieldallabeneta/app2:1
    environment:
      - POSTGRES_DB=microserviceuserdata_dev  
      - POSTGRES_LOGIN=postgres
      - SWAGGER_ENABLED=true
    depends_on:
      - db
    networks:
      - microservicewallet_dev
    ports:
      - "8081:8080"    

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data/develop:/data/db 
    networks:
      - microservicewallet_dev
      
  app1:
    image: danieldallabeneta/app1:1.0.0
    environment:
      - SWAGGER_ENABLED=true
    depends_on:
      - mongo
      - app2
    networks:
      - microservicewallet_dev
    ports:
      - "5050:5000"

  app3:
    image: danieldallabeneta/app3:1.0.0
    environment:
      - SWAGGER_ENABLED=true
    depends_on:
      - app1
      - app2  
    networks:
      - microservicewallet_dev 
    ports:
      - "5011:5010"
  
  # gateway:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   networks:
  #     - microservicewallet  
  #   depends_on:
  #     - app1
  #     - app2 

volumes:
  postgres-data:
  mongo-data:  
secrets:
  postgres-password:
    file: postgres/password.txt
networks:
  microservicewallet_dev: