services:

  db:
    image: postgres:latest
    secrets:
      - postgres-password
    volumes:
      - ./postgres-data/main:/var/lib/postgresql/data
    networks:
      - microservicewallet
    environment:
      - POSTGRES_DB=microserviceuserdata
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password

  app2:
    image: danieldallabeneta/app2:1
    environment:
      - POSTGRES_DB=microserviceuserdata 
      - POSTGRES_LOGIN=postgres 
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    depends_on:
      - db   
    networks:
      - microservicewallet
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data/main:/data/db 
    networks:
      - microservicewallet
      
  app1:
    image: danieldallabeneta/app1:1.0.0
    depends_on:
      - mongo
      - app2
    networks:
      - microservicewallet
    ports:
      - "5000:5000"

  app3:
    image: danieldallabeneta/app3:1.0.0
    depends_on:
      - app1
      - app2  
    networks:
      - microservicewallet 
    ports:
      - "5010:5010"     
  
  # gateway:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   networks:
  #     - microservicewallet  
  #   depends_on:
  #     - app1
  #     - app2 

volumes:
  postgres-data:
  mongo-data:  
secrets:
  postgres-password:
    file: postgres/password.txt
networks:
  microservicewallet: