services:

  db:
    image: postgres:latest
    secrets:
      - postgres-password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - microservicewallet
    environment:
      - POSTGRES_DB=microserviceuserdata
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password

  app2:
    build: 
      context: MicroServiceUserData
      target: builder
    environment:
      - POSTGRES_DB=microserviceuserdata  
      - SWAGGER_ENABLED=true
    depends_on:
      - db 
    command: ["./wait-for-it.sh", "postgres:5432", "--", "java", "-jar",  "/app2/target/MicroServiceUserData-0.0.1-SNAPSHOT.jar"]    
    networks:
      - microservicewallet
    ports:
      - "8100:8080"

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db 
    networks:
      - microservicewallet
      
  app1:
    build:
      context: app1
      target: builder
    environment:
      - SWAGGER_ENABLED=true
    volumes:
      - ./app1:/src
    depends_on:
      - mongo
      - app2
    networks:
      - microservicewallet
    ports:
      - "5050:5000"

  app3:
    build:
      context: app3
      target: builder 
    environment:
      - SWAGGER_ENABLED=true
    depends_on:
      - app1
      - app2  
    networks:
      - microservicewallet 
    ports:
      - "5100:5010"     
  
  # gateway:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   networks:
  #     - microservicewallet  
  #   depends_on:
  #     - app1
  #     - app2 

volumes:
  postgres-data:
  mongo-data:  
secrets:
  postgres-password:
    file: postgres/password.txt
networks:
  microservicewallet: