name: Auto PR from Develop to Release

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: |
          git config --global user.name 'Daniel Valdo'
          git config --global user.email 'danielvaldo@hotmail.com'

      - name: Create Pull Request to Release
        uses: gh-actions/create-pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR: Merge Develop into Release"
          base: release
          head: develop          
          title: "Automated PR: Merge Develop into Release"
          body: "This is an automated pull request to merge changes from Develop into Release."
          delete-branch: false
