name: Pipeline_dev

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract Version
        id: get_version
        run: |
          cd ./MicroServiceUser/app1
          echo "VERSION=$(grep -oP "(?<=__version__ = \")\d+\.\d+\.\d+" ./__version__.py)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd ./MicroServiceUser/app1
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests with coverage
        run: |
          cd ./MicroServiceUser/app1
          pytest -v --cov=./ --cov-report=xml --cov-report=html

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >           
            -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY_APP1}}
            -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}}
            -Dsonar.projectBaseDir=./MicroServiceUser/app1
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP1 }}
      
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
      - name: Build Docker image APP1
        run: |
          cd ./MicroServiceUser/app1
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{ env.VERSION }} .
          
      - name: Push Docker image to Docker Hub
        run: |
          cd ./MicroServiceUser/MicroServiceUserData
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{ env.VERSION }}