name: Pipeline_main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
              
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'

      - name: Extract Version
        id: get_version
        run: |
          echo "VERSION=$(grep -oP "(?<=__version__ = \")\d+\.\d+\.\d+" ./MicroServiceUser/app1/__version__.py)" >> $GITHUB_ENV
      
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
      - name: Build Docker image APP1
        run: |
          cd ./MicroServiceUser/app1
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{ env.VERSION }} .
          
      - name: Push Docker image to Docker Hub
        run: |
          cd ./MicroServiceUser/app1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{ env.VERSION }}
    
  app3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4       
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'

      - name: Extract Version
        id: get_version
        run: |
          echo "VERSION=$(grep -oP "(?<=__version__ = \")\d+\.\d+\.\d+" ./MicroServiceUser/app3/__version__.py)" >> $GITHUB_ENV
            
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
      - name: Build Docker image APP3
        run: |
          cd ./MicroServiceUser/app3
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app3:${{ env.VERSION }} .
          
      - name: Push Docker image to Docker Hub
        run: |
          cd ./MicroServiceUser/app3
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app3:${{ env.VERSION }}

  app2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'   
              
      - name: Get project version
        id: vars
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV        
                  
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
      - name: Build Docker image APP2
        run: |
          cd ./MicroServiceUser/MicroServiceUserData
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app2:${{ env.VERSION }} .
          
      - name: Push Docker image to Docker Hub
        run: |
          cd ./MicroServiceUser/MicroServiceUserData
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app2:${{ env.VERSION }}